# Generated by Django 5.0.6 on 2024-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Katalog', 'verbose_name_plural': 'Kataloglar'},
        ),
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='Ikonkasi'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Katalog nomi'),
        ),
    ]
