# Generated by Django 5.0.6 on 2025-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_genre_options_genre_icon_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='book_app.genre', verbose_name='Kataloglar'),
        ),
    ]
