# Generated by Django 5.0.6 on 2025-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_remove_book_genres_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='library_admin_checked',
            field=models.BooleanField(default=False, verbose_name='Kutubxonachi tasdiqladimi?'),
        ),
    ]
