# Generated by Django 5.0.6 on 2025-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_rental_library_admin_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Olgan sana'),
        ),
    ]
