# Generated by Django 5.0.6 on 2025-01-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_rental_created_at_rental_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, default=2020, null=True, verbose_name='Chop etilgan sana'),
        ),
    ]
