# Generated by Django 5.0.6 on 2025-01-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id'], 'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
    ]
