# Generated by Django 5.0.6 on 2025-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Kitob nomi'),
        ),
    ]
