# Generated by Django 5.0.6 on 2026-03-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivmi?'),
        ),
    ]
