# Generated by Django 5.0.6 on 2026-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_genre_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarilgan sana'),
        ),
    ]
