# Generated by Django 5.2.15 on 2026-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0014_rental_due_date_alter_rental_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
