# Generated by Django 5.2.15 on 2026-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0015_book_view_count'),
        ('user_app', '0011_alter_role_options_employeprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['full_name'], 'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Katalog', 'verbose_name_plural': 'Kataloglar'},
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name="O'rtacha reyting"),
        ),
        migrations.AddField(
            model_name='book',
            name='download_allowed',
            field=models.BooleanField(default=False, verbose_name='Yuklab olishga ruxsat'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktivmi?'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chop etilgan yili'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Baholar soni'),
        ),
        migrations.AddField(
            model_name='book',
            name='reading_mode',
            field=models.CharField(choices=[('PHYSICAL', 'Jismoniy'), ('DIGITAL', 'Raqamli'), ('BOTH', 'Ikkalasi')], default='PHYSICAL', max_length=10, verbose_name='Foydalanish turi'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Ism Familiya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Kitob yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chop etilgan sana (eski)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='copy',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Mavjudmi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Qaytarish muddati'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Qaytarilgan sana'),
        ),
        migrations.AddConstraint(
            model_name='copy',
            constraint=models.UniqueConstraint(fields=('book', 'inventory_number'), name='uniq_inventory_per_book'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(condition=models.Q(('return_date__isnull', True)), fields=('copy',), name='uniq_active_rental_per_copy'),
        ),
    ]
