# Generated by Django 5.0.6 on 2024-12-20 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_employee_user_remove_libraryadmin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_role',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rol nomi'),
        ),
        migrations.CreateModel(
            name='EmployeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(blank=True, null=True, verbose_name="Bo'lim")),
                ('position', models.TextField(blank=True, null=True, verbose_name='Lavozim')),
                ('roles', models.ManyToManyField(blank=True, null=True, to='user_app.role', verbose_name='Xodim rollari')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fakultet')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bosqich')),
                ('semester', models.CharField(blank=True, max_length=100, null=True, verbose_name='Semestr')),
                ('education_form', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'lim shakli")),
                ('education_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'lim turi")),
                ('payment_form', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov shakli")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
