# Generated by Django 5.0.6 on 2024-12-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_employeprofile_user_alter_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeprofile',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employes', to='user_app.role', verbose_name='Hozirgi rol'),
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employe_profiles', to='user_app.role', verbose_name='Xodim rollari'),
        ),
    ]
