# Generated by Django 5.0.6 on 2024-12-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_employeprofile_current_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jshshir',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
    ]
