# Generated by Django 5.0.6 on 2025-01-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_remove_user_jshshir_remove_user_passport_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeprofile',
            options={'verbose_name': 'Hodim', 'verbose_name_plural': 'Hodimlar'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Rollar'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
