# Generated by Django 5.2.15 on 2026-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_employeprofile_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Rollar'},
        ),
        migrations.AddField(
            model_name='employeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AddField(
            model_name='employeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='HEMIS UUID'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Universitet ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Admin panelga kirish'),
        ),
    ]
