# Generated by Django 5.2.15 on 2026-06-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_app', '0015_book_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='book_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qish tarixi",
                'verbose_name_plural': "O'qish tarixi",
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('READ', "O'qish"), ('LISTEN', 'Tinglash')], default='READ', max_length=10)),
                ('position', models.FloatField(default=0, verbose_name='Joriy joy (sahifa yoki soniya)')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='Foiz')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='book_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qish jarayoni",
                'verbose_name_plural': "O'qish jarayonlari",
                'unique_together': {('user', 'book', 'mode')},
            },
        ),
    ]
