# Generated by Django 5.2.15 on 2026-06-18 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_alter_author_options_alter_genre_options_and_more'),
        ('reading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['book', 'opened_at'], name='reading_rea_book_id_c59940_idx'),
        ),
    ]
