# Generated by Django 5.0.6 on 2026-06-17 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_app', '0014_rental_due_date_alter_rental_return_date'),
        ('user_app', '0010_alter_employeprofile_options_alter_role_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_days', models.PositiveIntegerField(default=14, verbose_name='Ijara muddati (kun)')),
                ('reservation_hold_days', models.PositiveIntegerField(default=2, verbose_name='Navbat ushlab turish (kun)')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Kuniga jarima (so'm)")),
                ('max_active_rentals', models.PositiveIntegerField(default=5, verbose_name='Bir vaqtda maksimal ijara')),
            ],
            options={
                'verbose_name': 'Kutubxona sozlamasi',
                'verbose_name_plural': 'Kutubxona sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_overdue', models.PositiveIntegerField(default=0, verbose_name='Kechikkan kunlar')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Summa (so'm)")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan sana")),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='book_app.rental', verbose_name='Ijara')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='user_app.studentprofile', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': 'Jarimalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=10, verbose_name='Holati')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="So'ralgan sana")),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan sana')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='book_app.book', verbose_name='Kitob')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kim hal qildi')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='book_app.rental', verbose_name='Ijara')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='user_app.studentprofile', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Ijara so'rovi",
                'verbose_name_plural': "Ijara so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Navbatda'), ('AVAILABLE', "Bo'shadi (ushlab turilmoqda)"), ('FULFILLED', 'Bajarildi'), ('EXPIRED', "Muddati o'tdi"), ('CANCELLED', 'Bekor qilingan')], default='WAITING', max_length=10, verbose_name='Holati')),
                ('hold_until', models.DateTimeField(blank=True, null=True, verbose_name='Ushlab turish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Navbatga yozilgan sana')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='book_app.book', verbose_name='Kitob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='user_app.studentprofile', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
                'ordering': ['created_at'],
            },
        ),
    ]
