# Generated by Django 5.2.15 on 2026-06-18 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_alter_author_options_alter_genre_options_and_more'),
        ('circulation', '0001_initial'),
        ('user_app', '0011_alter_role_options_employeprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='PENDING', max_length=10, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Navbatda'), ('AVAILABLE', "Bo'shadi (ushlab turilmoqda)"), ('FULFILLED', 'Bajarildi'), ('EXPIRED', "Muddati o'tdi"), ('CANCELLED', 'Bekor qilingan')], db_index=True, default='WAITING', max_length=10, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['book', 'status'], name='circulation_book_id_56d8d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('student', 'book'), name='uniq_pending_request_per_student_book'),
        ),
    ]
