# Generated by Django 5.2.15 on 2026-06-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REQUEST_APPROVED', "So'rov tasdiqlandi"), ('REQUEST_REJECTED', "So'rov rad etildi"), ('RESERVATION_AVAILABLE', "Navbat bo'shadi"), ('DUE_SOON', 'Muddat yaqin'), ('OVERDUE', "Muddat o'tdi"), ('FINE', 'Jarima'), ('REVIEW_APPROVED', 'Sharh tasdiqlandi'), ('GENERAL', 'Umumiy')], default='GENERAL', max_length=24, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.CharField(blank=True, max_length=400, verbose_name='Matn')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Havola')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
